services:
  postgres:
    image: postgres:latest
    container_name: lib-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "library"
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
