version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: lib-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "library"
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
